### ISSUE TITLE
README should have end-to-end usage example

### ISSUE THREAD

**Issue by mikepurvis** [mikepurvis/catkin_tools_python#6]

**Comment by asmodehn** [comment]
Yes please :)

I'm looking forward to that so we can compare this and https://github.com/asmodehn/catkin_pip with meaningful examples.

FYI I am using cookiecutter templates as tests https://github.com/asmodehn/catkin_pip/tree/devel/test, I thought you might want to do the same...

**Comment by mikepurvis** [comment]
Hey @asmodehn, please give it a look. The example is now pretty comprehensive.

**Comment by asmodehn** [comment]
Thanks ! I ll play with it...
